---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---

```{r load-packages, include=FALSE}
library(dplyr)
library(magrittr)
library(knitr)
library(tidyverse)
```

## Loading and preprocessing the data
```{r}
raw <- read.csv("activity.csv", header = TRUE, sep = ",", na.strings = "NA")
raw <- mutate(raw, date = as.Date(date, "%Y-%m-%d"))
data <- na.omit(raw)
```
## What is mean total number of steps taken per day?
```{r}
aggregate(data$steps, by=list(data$date), FUN=sum)

plot(data$steps ~ data$date, type = "h")

aggregate(data$steps, by=list(data$date), FUN=mean)
aggregate(data$steps, by=list(data$date), FUN=median)
```
## What is the average daily activity pattern?
```{r}
plot(data$steps ~ data$interval, type = "l")
data[data$steps == max(data$steps),]
```
## Imputing missing values
```{r}
sum(is.na(raw$steps))
new <- raw
new[is.na(new)] <- 0

plot(data$steps ~ data$date, type = "h")

aggregate(new$steps, by=list(new$date), FUN=mean)
```
## Are there differences in activity patterns between weekdays and weekends?
```{r}
final <- mutate(data, weekday = weekdays(date) %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))
plot(final$date, final$steps, type = "l", col = final$weekday)
```